$(function(){
    $(".panel4").click(function(){
        $(".hide0").slideToggle(100)
        $(".show0").slideToggle(100)
    })
    $(".panel5").click(function(){
        $(".hide1").slideToggle(100)
        $(".show1").slideToggle(100)
    })
    $(".panel6").click(function(){
        $(".hide2").slideToggle(100)
        $(".show2").slideToggle(100)
    })
})
$(function(){
    $(".icon-info").hide()
    $(".icon-img").hover(function(){
        $(this).find(".icon-info").toggle(500)
    })
})